<RootWidget>
    canvas:
        Color:
            rgba: (0.6, 0.7, 1, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        Button:
            text:"Add Musics"
            width:100
            height:50
            on_release: root.add_music()
        Button:
            text:"Convert"
            width:200
            height:50
            on_release: root.convert_music()
        