<RootWidget>
    canvas:
        Color:
            rgba: (0.1, 0.1, 0.1, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    GridLayout:
        rows: 2
        pos: root.center
        Button:
            text:"Add Musics"
            width: 200
            height: 100
            on_release: root.add_music() 
        Button:
            text:"Convert"
            width: 200
            height: 100
            on_release: root.convert_music()
        